# name: Build and Deploy Frontend

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Build Angular app
#         run: nng build --configuration production

#       - name: Build and push Docker image Frontend
#         uses: docker/build-push-action@v3
#         with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/frontend:heroku
#           cache-from: type=local,src=/tmp/.buildx-cache
#           cache-to: type=local,dest=/tmp/.buildx-cache

#       - name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment: production
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Deploy to Heroku
#         uses: akhileshns/heroku-deploy@v3.13.15
#         with:
#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#           heroku_app_name: ${{ secrets.HEROKU_APP_NAME_FRONTEND }}  # Nombre único para la app frontend
#           heroku_email: ${{ secrets.HEROKU_EMAIL }}
